### ISSUE TITLE
Suction cup covers part of stop name

### ISSUE THREAD

**Issue by livebusglocal** [LiveBus/displayV1#10]
So we're positioning the suction cups and the upper suction cup covers the stop name if we put it on the left and it covers the date if we put it on the right. Do you think you could move the whole website down about half an inch so that this isn't a problem? Thanks

**Comment by maxtkc** [comment]
Will be fixed in big update (branch auto_dest). You'll have to let me know more or less once it's live.

**Comment by livebusglocal** [comment]
It looks pretty good - not actually necessary on most of them since full screen isn't working. If and when we do get them full screen (Amazon said they'll add the full screen feature back in a few months) we might want even a little more space on the top. Or you could put the date and time at the very top but centered and then have the stop name underneath them. Whatever you think, as long as both top corners are open.
