### ISSUE TITLE
Make the date more clear

### ISSUE THREAD

**Issue by jlawrenceCambridge** [LiveBus/displayV1#3]
Have the date in full format: August 16, 2018. If only numbers are allowed, use full date, and put on a separate line:

8/16/18

THANKS

**Comment by maxtkc** [comment]
Do we still want the time shown?

**Comment by maxtkc** [comment]
Keep in mind that we are on very small devices, so the less text the better, especially with long stop names.

**Comment by maxtkc** [comment]
If you don't like it, please reopen this issue instead of starting a new one.

**Comment by jlawrenceCambridge** [comment]
It looks great! But it's got September instead of August.

**Comment by jlawrenceCambridge** [comment]
I’m looking at it on my tablet now, and it looks good.

**Comment by jlawrenceCambridge** [comment]
Yes please!

**Comment by jlawrenceCambridge** [comment]
I did! I just reopened the issue.

**Comment by jlawrenceCambridge** [comment]
I see! I didn’t realize that you had already created a ticket. My bad.
