### ISSUE TITLE
*Scheduled Arrivals needs to be more visible

### ISSUE THREAD

**Issue by jlawrenceCambridge** [LiveBus/displayV1#6]
Hey Max:

Either move this up so that it is directly underneath the bottom-most bus (as opposed to at the bottom of the screen) OR (less prefereable) make it bold on the bottom of the screen.

**Comment by maxtkc** [comment]
Would it be good to be bold underneath the bottom-most bus?
>***Scheduled Arrivals**

**Comment by jlawrenceCambridge** [comment]
Perfect!
