### ISSUE TITLE
Some of the real-time arrivals are not coding correctly

### ISSUE THREAD

**Issue by jlawrenceCambridge** [LiveBus/displayV1#7]
Some of the buses that are actually running on real-time are showing up as a "scheduled arrival" - for example, see the below image. The next bus to arrive is showing as scheduled, the second as real-time, and the third as scheduled. 

![image](https://user-images.githubusercontent.com/42440459/44208926-d4c4c400-a12f-11e8-9c74-1a60d6172270.png)

**Comment by maxtkc** [comment]
Waiting for MBTA developers to respond by email on this one.

**Comment by livebusglocal** [comment]
Yeah sometimes it seems like it's showing both scheduled and real-time arrival times for the same bus.
![image](https://user-images.githubusercontent.com/42448750/44226677-a7433f00-a15e-11e8-8a06-0c0ec472e8c6.png)

**Comment by maxtkc** [comment]
I think I fixed this issue. It was showing the prediction and schedule for the same trips, but it should be good now. Let me know if there are any issues. I will close this for now, but do reopen it if something comes up.

**Comment by jlawrenceCambridge** [comment]
It seems good to me! I'll reopen this if it looks wonky at a later time
