### ISSUE TITLE
Use full space on each line of arrivals

### ISSUE THREAD

**Issue by jlawrenceCambridge** [LiveBus/displayV1#8]
Please make the font bigger so that the name of the stop is bigger and takes up more width of the screen. The arrivals should be centered so that they stretch further and have more space in between them.

**Comment by maxtkc** [comment]
Reopen if it isn't big enough, or if I misinterpreted something.

**Comment by jlawrenceCambridge** [comment]
There hasn't been a change when we view it.

**Comment by maxtkc** [comment]
I think you're right. How does it look now?

**Comment by jlawrenceCambridge** [comment]
That did it! Looks great. Thanks!
