### ISSUE TITLE
Harvard Station is kind of a mess

### ISSUE THREAD

**Issue by livebusglocal** [LiveBus/displayV1#9]
Before we install at Dickson Bros, we should fix the page for Harvard Bus Tunnel.
1. The stop names should say "Harvard Upper Bus Tunnel" and "Harvard Lower Bus Tunnel" - right now they both just say "Harvard"
2. Show departures only - because the buses drop off passengers in the Lower Tunnel and pick up in the Upper Tunnel (or vice versa) the website currently shows both arrivals and departures for all the bus routes. No one will need to know about the arrivals, just the departures, so figure out how to filter those out (probably just permanently hard-code it since it's a unique stop).
3. There are too many bus routes to fit on one screen so once you fix number 2 try to split the upper tunnel into two pages.
Thanks
Ezra

**Comment by livebusglocal** [comment]
We can wait until next Thursday to install at Dickson, so prioritize the other stuff.

**Comment by maxtkc** [comment]
This one is quite tricky. I still need to figure out how to do it. For the titles, that's more of a MBTA api issue... Maybe they would be interested in changing it. We could technicaly hard-code it, but that doesn't seem like the best fix for such an issue. It's okay if it has two pages anyways, because it's so large.

**Comment by livebusglocal** [comment]
Our internship ends tomorrow so we have to install it by then.

**Comment by maxtkc** [comment]
Will be fixed in next big update (branch auto_dest).

**Comment by livebusglocal** [comment]
Is there any way you could fix Harvard (remove the routes with "Harvard" as the destination and change the stop names to specify upper and lower bus tunnels) today? We're trying to install the tablet at Dickson this afternoon and we don't want it to be confusing. If you can't do both worry about removing the arrival buses first.
